# 3.3 Extract all Testudines family details save into csv file.

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import requests
import time

driver = webdriver.Chrome()
url = "https://www.scrapethissite.com/pages/frames/"
driver.get(url)
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find_all('div',class_='col-md-4 turtle-family-card')# all
frm
list =[]
for i in frm[0:14]:
    base_url = 'https://www.scrapethissite.com/'
    dict = {
        'name':'',
        'url':'',
        'img_url':'',
        "detail":'',
    }
    dict ['img_url']=i.find('img')['src']
    dict ['inner_url']=base_url + i.find('a')['href']
    dict ['name']=i.find('h3').text
    
    inner_url = dict["inner_url"] # inner url
    headers = {"User-Agent": "Mozilla/5.0"}
    
    resp = requests.get(inner_url, headers=headers)

    soup_nw = BeautifulSoup(resp.text, "html.parser")
    # soup_nw
    dict["detail"]=soup_nw.find('p').text.strip()# all url details
    
    list.append(dict)
df = pd.DataFrame(list)
df
df.to_csv("question_no_3.3(frames).csv", index=False)    
df

# 3.4 Extract all Testudines family details of first column save into csv file.

In [3]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import requests
import time

driver = webdriver.Chrome()
url = "https://www.scrapethissite.com/pages/frames/"
driver.get(url)
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find_all('div',class_='col-md-4 turtle-family-card')# all
frm
list =[]
for i in frm[0:14:3]:
    base_url = 'https://www.scrapethissite.com/'
    dict = {
        'name':'',
        'url':'',
        'img_url':'',
        "detail":'',
    }
    dict ['img_url']=i.find('img')['src']
    dict ['inner_url']=base_url + i.find('a')['href']
    dict ['name']=i.find('h3').text
    
    inner_url = dict["inner_url"] # inner url
    headers = {"User-Agent": "Mozilla/5.0"}
    
    resp = requests.get(inner_url, headers=headers)

    soup_nw = BeautifulSoup(resp.text, "html.parser")
    # soup_nw
    dict["detail"]=soup_nw.find('p').text.strip()# all url details
    
    list.append(dict)
df = pd.DataFrame(list)
df

,name,url,img_url,detail,inner_url
0,Carettochelyidae,,https://upload.wikimedia.org/wikipedia/commons...,The Carettochelyidae family of turtles — more ...,https://www.scrapethissite.com//pages/frames/?...
1,Dermatemydidae,,https://upload.wikimedia.org/wikipedia/commons...,The Dermatemydidae family of turtles — more co...,https://www.scrapethissite.com//pages/frames/?...
2,Geoemydidae,,https://upload.wikimedia.org/wikipedia/commons...,The Geoemydidae family of turtles — more commo...,https://www.scrapethissite.com//pages/frames/?...
3,Testudinidae,,https://upload.wikimedia.org/wikipedia/commons...,The Testudinidae family of turtles — more comm...,https://www.scrapethissite.com//pages/frames/?...
4,Pelomedusidae,,https://upload.wikimedia.org/wikipedia/commons...,The Pelomedusidae family of turtles — more com...,https://www.scrapethissite.com//pages/frames/?...

# 3.5 Extract all Testudines family details of Second column save into csv file.

In [4]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import requests
import time

driver = webdriver.Chrome()
url = "https://www.scrapethissite.com/pages/frames/"
driver.get(url)
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find_all('div',class_='col-md-4 turtle-family-card')# all
frm
list =[]
for i in frm[1:14:3]:
    base_url = 'https://www.scrapethissite.com/'
    dict = {
        'name':'',
        'url':'',
        'img_url':'',
        "detail":'',
    }
    dict ['img_url']=i.find('img')['src']
    dict ['inner_url']=base_url + i.find('a')['href']
    dict ['name']=i.find('h3').text
    
    inner_url = dict["inner_url"] # inner url
    headers = {"User-Agent": "Mozilla/5.0"}
    
    resp = requests.get(inner_url, headers=headers)

    soup_nw = BeautifulSoup(resp.text, "html.parser")
    # soup_nw
    dict["detail"]=soup_nw.find('p').text.strip()# all url details
    
    list.append(dict)
df = pd.DataFrame(list)
df

,name,url,img_url,detail,inner_url
0,Cheloniidae,,https://upload.wikimedia.org/wikipedia/commons...,The Cheloniidae family of turtles — more commo...,https://www.scrapethissite.com//pages/frames/?...
1,Dermochelyidae,,https://upload.wikimedia.org/wikipedia/commons...,The Dermochelyidae family of turtles — more co...,https://www.scrapethissite.com//pages/frames/?...
2,Kinosternidae,,https://upload.wikimedia.org/wikipedia/commons...,The Kinosternidae family of turtles — more com...,https://www.scrapethissite.com//pages/frames/?...
3,Trionychidae,,https://upload.wikimedia.org/wikipedia/commons...,The Trionychidae family of turtles — more comm...,https://www.scrapethissite.com//pages/frames/?...
4,Podocnemididae,,https://upload.wikimedia.org/wikipedia/commons...,The Podocnemididae family of turtles — more co...,https://www.scrapethissite.com//pages/frames/?...

# 3.6 Extract all Testudines family details of thirst column save into csv file.

In [5]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import requests
import time

driver = webdriver.Chrome()
url = "https://www.scrapethissite.com/pages/frames/"
driver.get(url)
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find_all('div',class_='col-md-4 turtle-family-card')# all
frm
list =[]
for i in frm[2:14:3]:
    base_url = 'https://www.scrapethissite.com/'
    dict = {
        'name':'',
        'url':'',
        'img_url':'',
        "detail":'',
    }
    dict ['img_url']=i.find('img')['src']
    dict ['inner_url']=base_url + i.find('a')['href']
    dict ['name']=i.find('h3').text
    
    inner_url = dict["inner_url"] # inner url
    headers = {"User-Agent": "Mozilla/5.0"}
    
    resp = requests.get(inner_url, headers=headers)

    soup_nw = BeautifulSoup(resp.text, "html.parser")
    # soup_nw
    dict["detail"]=soup_nw.find('p').text.strip()# all url details
    
    list.append(dict)
df = pd.DataFrame(list)
df

,name,url,img_url,detail,inner_url
0,Chelydridae,,https://upload.wikimedia.org/wikipedia/commons...,The Chelydridae family of turtles — more commo...,https://www.scrapethissite.com//pages/frames/?...
1,Emydidae,,https://upload.wikimedia.org/wikipedia/commons...,The Emydidae family of turtles — more commonly...,https://www.scrapethissite.com//pages/frames/?...
2,Platysternidae,,https://upload.wikimedia.org/wikipedia/commons...,The Platysternidae family of turtles — more co...,https://www.scrapethissite.com//pages/frames/?...
3,Chelidae,,https://upload.wikimedia.org/wikipedia/commons...,The Chelidae family of turtles — more commonly...,https://www.scrapethissite.com//pages/frames/?...