In [9]:
import pandas as pd
Data = [
{
    'roll number': "T0001",
    'name': "Asif kasi",
    'father name': "qasim ali kasi",
    'class': "python",
},

{
        'roll number': "S0002",
    'name': "Abdur rehman",
    'father name': "Shakir",
    'class': "python",
},
{
        'roll number': "S0003",
    'name': "A Maaz",
    'father name': "M Naeem",
    'class': "python",

},
{
        'roll number': "S0004",
    'name': "Sheraz",
    'father name': "Muhammad Khan",
    'class': "python",
},
{
        'roll number': "S0005",
    'name': "Farhan",
    'father name': "Adil umar",
    'class': "python",

},
{
        'roll number': "S0006",
    'name': "Wahab",
    'father name': "Abdul Sattar",
    'class': "python",
},
{
    'roll number': "S0007",
    'name': "Asim",
    'father name': "Zahir hussain",
    'class': "python",
},
{
    'roll number': "S0008",
    'name': "Shariq",
    'father name': "Farooq",
    'class': "python",
},

]

print(Data)
df = pd.DataFrame(Data)
df

[{'roll number': 'T0001', 'name': 'Asif kasi', 'father name': 'qasim ali kasi', 'class': 'python'}, {'roll number': 'S0002', 'name': 'Abdur rehman', 'father name': 'Shakir', 'class': 'python'}, {'roll number': 'S0003', 'name': 'A Maaz', 'father name': 'M Naeem', 'class': 'python'}, {'roll number': 'S0004', 'name': 'Sheraz', 'father name': 'Muhammad Khan', 'class': 'python'}, {'roll number': 'S0005', 'name': 'Farhan', 'father name': 'Adil umar', 'class': 'python'}, {'roll number': 'S0006', 'name': 'Wahab', 'father name': 'Abdul Sattar', 'class': 'python'}, {'roll number': 'S0007', 'name': 'Asim', 'father name': 'Zahir hussain', 'class': 'python'}, {'roll number': 'S0008', 'name': 'Shariq', 'father name': 'Farooq', 'class': 'python'}]

  roll number          name     father name   class
0       T0001     Asif kasi  qasim ali kasi  python
1       S0002  Abdur rehman          Shakir  python
2       S0003        A Maaz         M Naeem  python
3       S0004        Sheraz   Muhammad Khan  python
4       S0005        Farhan       Adil umar  python
5       S0006         Wahab    Abdul Sattar  python
6       S0007          Asim   Zahir hussain  python
7       S0008        Shariq          Farooq  python

In [10]:
df.to_csv('students_data.csv', index=False)

In [ ]:
import pandas as pd

Data = [
{
    'roll number': "T0001",
    'name': "Asif kasi",
    'father name': "qasim ali kasi",
    'class': "python",
},

{
        'roll number': "S0002",
    'name': "Abdur rehman",
    'father name': "Shakir",
    'class': "python",
},
{
        'roll number': "S0003",
    'name': "A Maaz",
    'father name': "M Naeem",
    'class': "python",

},
{
        'roll number': "S0004",
    'name': "Sheraz",
    'father name': "Muhammad Khan",
    'class': "python",
},
{
        'roll number': "S0005",
    'name': "Farhan",
    'father name': "Adil umar",
    'class': "python",

},
{
        'roll number': "S0006",
    'name': "Wahab",
    'father name': "Abdul Sattar",
    'class': "python",
},
{
    'roll number': "S0007",
    'name': "Asim",
    'father name': "Zahir hussain",
    'class': "python",
},
{
    'roll number': "S0008",
    'name': "Shariq",
    'father name': "Farooq",
    'class': "python",
},

]

print(Data)
df = pd.DataFrame(Data)
df
df.to_csv('students_data.csv', mode='a+', index=False)

[{'roll number': 'T0001', 'name': 'Asif kasi', 'father name': 'qasim ali kasi', 'class': 'python'}, {'roll number': 'S0002', 'name': 'Abdur rehman', 'father name': 'Shakir', 'class': 'python'}, {'roll number': 'S0003', 'name': 'A Maaz', 'father name': 'M Naeem', 'class': 'python'}, {'roll number': 'S0004', 'name': 'Sheraz', 'father name': 'Muhammad Khan', 'class': 'python'}, {'roll number': 'S0005', 'name': 'Farhan', 'father name': 'Adil umar', 'class': 'python'}, {'roll number': 'S0006', 'name': 'Wahab', 'father name': 'Abdul Sattar', 'class': 'python'}, {'roll number': 'S0007', 'name': 'Asim', 'father name': 'Zahir hussain', 'class': 'python'}, {'roll number': 'S0008', 'name': 'Shariq', 'father name': 'Farooq', 'class': 'python'}]

In [13]:
roll_number = input("Enter your roll number: ")
first_name = input("Enter your name: ")
last_name = input("Enter your father name: ")
class_name = input("Enter your class: ")

Data.append(
    {
        'roll number': roll_number,
        'name': first_name,
        'father name': last_name,
        'class': class_name,
    }
)
df = pd.DataFrame(Data)
df

  roll number          name     father name   class
0       T0001     Asif kasi  qasim ali kasi  python
1       S0002  Abdur rehman          Shakir  python
2       S0003        A Maaz         M Naeem  python
3       S0004        Sheraz   Muhammad Khan  python
4       S0005        Farhan       Adil umar  python
5       S0006         Wahab    Abdul Sattar  python
6       S0007          Asim   Zahir hussain  python
7       S0008        Shariq          Farooq  python
8        0001        shawiz            qyub  python

In [14]:
df.to_csv('students_data.csv', mode='a+', index=False)