# a3. Download pdfs from https://www.nbp.com.pk/RATESHEET/index.aspx
# a4. Save all images form Wikipedia q2.

In [41]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = " https://www.nbp.com.pk/RATESHEET/index.aspx"


response = requests.get(url)
response.status_code

# # from urllib.request import urlopen
# import requests
# from bs4 import BeautifulSoup
# import re


# header={
#     "User-Agent": "Baiduspider"
# }

# html = requests.get('https://www.nbp.com.pk/RATESHEET/index.aspx',headers=header)
# # html = requests.get('https://www.imdb.com/chart/top/')

# html.status_code

200

In [20]:
soup = BeautifulSoup(response.text, "html.parser")
print(soup.prettify())

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <title>
   Rate Sheets - NBP
  </title>
  <meta content="IE=EmulateIE7" http-equiv="X-UA-Compatible"/>
  <!-- This tag enables compatiility view -->
  <link href="../SideTable.css" rel="stylesheet" type="text/css"/>
  <link href="../StyleSheet2.css" rel="stylesheet" type="text/css"/>
  <style type="text/css">
   body {
	  margin: 0;
	  padding: 0;
      }
  </style>
  <style type="text/css">
   .style556
        {
            width: 100%;
        }
  </style>
 </head>
 <body>
  <script src="../NMenu/stmenu.js" type="text/javascript">
  </script>
  <meta content="IE=EmulateIE7" http-equiv="X-UA-Compatible"/>
  <!-- This tag enables compatiility view -->
  <style type="text/css">
   body {
	margin: 0;
	padding: 0;


      }
  </style>
  <style type="text/css">
   .TopFont {
	font-family: Verdana, Geneva, sans-serif;
	font-weight: bold;
	font-size: 11px;
	color: #333;
	text-align:center;
	vertical-align:middle;
}
.promptlink{
color: #fff;
    text-decoration: none;
    background: #f8aa24;
    padding: 5px;
    border-radius: 5px;
}
  </style>
  <style type="text/css">
   .TopFont2 {
	font-family: Verdana, Geneva, sans-serif;
	font-weight: bold;
	font-size: 11px;
	color:#FFF;
	text-align:center;
	vertical-align:middle;
}
  </style>
  <style type="text/css">
   <!--
.headerLink:link {
	color: #333;
	text-decoration: none;
}
.headerLink:visited {
	text-decoration: none;
	color: #333;
}
.headerLink:hover {
	color: #F7A820;
	text-decoration: underline;
	}
.headerLink:active {
	text-decoration: none;
}

a img { border: none; } <!-- for removing hyperlink border from images -->

-->
  </style>
  <style type="text/css">
   <!--
.headerLink2:link {
	color:#FC0;
	text-decoration: none;
}
.headerLink2:visited {
	text-decoration: none;
	color: #FC0;
}
.headerLink2:hover {
	color:#FFF;
	text-decoration: underline;
	}
.headerLink2:active {
	text-decoration: none;
}



-->
  </style>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-114735244-1">
  </script>
  <script>
   window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-114735244-1');
  </script>
  <!---------- border table----------------------->
  <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
   <tr>
    <td>
     <!-- first main table>-->
     <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
      <tr bgcolor="#F7A820" height="7px" valign="middle">
       <td>
       </td>
      </tr>
      <tr bgcolor="Black" height="3px" valign="middle">
       <td>
       </td>
      </tr>
      <tr valign="middle">
       <td>
        <table align="center" cellpadding="0" cellspacing="0" width="100%">
         <!-- English\Urdu Row-->
         <!--   <tr height="25" bgcolor="#FFFFFF">
		          <td  align="left" valign="middle" >&nbsp;</td>
		          <td ></td>
		          <td align="right" valign="middle"><table width="150" border="0">
		            <tr>
		              <td class="TopFont"><a href="../index.aspx" class="headerLink">English</a></td>
		              <td class="TopFont"><a href="../indexUrdu.aspx"><img src="../MainPageImages/UrduMain3.gif" width="33" height="17" /></a></td>
	                </tr>
	              </table></td>
		          </tr>
                  <!-- End English\Urdu Row-->
         <tr bgcolor="#FFFFFF" height="25">
          <td align="left" valign="middle">
          </td>
          <td>
          </td>
          <td align="right" valign="middle">
           <table align="right" border="0" width="150">
            <tr>
             <td class="TopFont">
              <a class="headerLink" href="../index.aspx">
               English
              </a>
             </td>
             <td class="TopFont">
              <a href="../indexUrdu.aspx">
               <img height="17" src="../MainPageImages/UrduMain3.gif" width="33"/>
              </a>
             </td>
            </tr>
           </table>
          </td>
         </tr>
         <tr bgcolor="#D6D6D6" height="35">
          <td align="left" valign="middle" width="25%">
           <img height="20" src="../MainPageImages/NBPntranetImg1.jpg" width="200"/>
          </td>
          <td width="11%">
          </td>
          <td align="right" valign="middle" width="64%">
           <table border="0" cellpadding="0" cellspacing="0" width="100%">
            <tr>
             <td align="center" class="TopFont" valign="middle" width="6%">
              <a class="headerLink" href="../index.aspx">
               Home
              </a>
             </td>
             <td align="center" id="myCol" valign="middle" width="12%">
              <div id="myDIV">
               <span class="TopFont">
                <a class="headerLink" href="../hr-intranet/index.aspx">
                 HR Intranet
                </a>
               </span>
              </div>
             </td>
             <td align="center" valign="middle" width="8%">
              <span class="TopFont">
               <a class="headerLink" href="../careers/index.aspx">
                Careers
               </a>
              </span>
             </td>
             <td align="center" valign="middle" width="11%">
              <span class="TopFont">
               <a class="headerLink" href="../contact/index.aspx">
                Contact Us
               </a>
              </span>
             </td>
             <td align="center" valign="middle" width="17%">
              <span class="TopFont">
               <a class="headerLink" href="../BRNTWRK/DomesticBrLocator.aspx">
                Branch Network
               </a>
              </span>
             </td>
             <td align="center" valign="middle" width="8%">
              <span class="TopFont">
               <a class="headerLink" href="../SITEMAP/index.aspx">
                Site Map
               </a>
              </span>
             </td>
             <td align="center" class="TopFont" valign="middle" width="8%">
              <a class="headerLink" href="../SEARCH/index.aspx">
               Search
              </a>
             </td>
             <td align="center" class="TopFont" valign="middle" width="6%">
              <a class="promptlink" href="../enquiries/index.aspx">
               Feedback
              </a>
             </td>
             <td align="center" class="TopFont" valign="middle" width="10%">
              <a href="https://ibanking.nbp.com.pk/">
               <img alt="Qries" height="27" src="../images/ibanking.png" width="91"/>
              </a>
             </td>
            </tr>
           </table>
          </td>
         </tr>
        </table>
       </td>
      </tr>
     </table>
     <!-- End First main table>-->
     <!-- Second main table>-->
     <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
      <tr>
       <td>
        <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
         <tr bgcolor="#000000" height="20" valign="middle">
          <td width="20%">
          </td>
          <td width="80%">
           <table align="right" border="0" cellpadding="0" cellspacing="0" width="95%">
            <tr>
             <td class="TopFont2" width="25%">
              <a class="headerLink2" href="../csr/index.aspx">
               Corporate Social Responsibility
              </a>
             </td>
             <td class="TopFont2" width="20%">
              <a class="headerLink2" href="../CorporateBanking/index.aspx">
               Corporate Banking
              </a>
             </td>
             <td class="TopFont2" width="20%">
              <a class="headerLink2" href="../InvestorRelations/index.aspx">
               Investor Relations
              </a>
             </td>
             <!-- <td class="TopFont2" width="20%"><a href="../InvestorInformation/index.aspx" class="headerLink2">Investor Information</a></td>-->
             <td class="TopFont2" width="15%">
              <a class="headerLink2" href="../Treasury/index.aspx">
               Treasury
              </a>
             </td>
            </tr>
           </table>
          </td>
         </tr>
        </table>
       </td>
      </tr>
      <tr bgcolor="#F7A820" height="2px">
       <td>
       </td>
      </tr>
     </table>
     <!-- End Second main table>-->
     <!-- 3rd main table-->
     <table border="0" cellpadding="0" cellspacing="0" width="100%">
      <tr>
       <td align="left" valign="middle" width="10%">
        <a href="../index.aspx">
         <img height="85" src="../images/NBPFinalBand-2018-left.jpg" width="338"/>
        </a>
       </td>
       <td align="center" background="../images/NBPFinalBand-2017-middle.jpg" valign="middle" width="80%">
        <img alt="NBP UAN" height="44" src="../images/NBPFinalBand-2018-middle.jpg" width="140"/>
       </td>
       <td align="right" valign="middle" width="10%">
        <a href="../index.aspx">
         <img height="85" src="../images/NBPFinalBand-2018-right.jpg" width="343"/>
        </a>
       </td>
      </tr>
     </table>
     <!-------------- end 3rd main table>



              <!-- fourth big table-------->
     <table align="center" border="0" bordercolor="#111111" cellpadding="0" cellspacing="0" id="AutoNumber1" style="border-collapse: collapse" width="100%">
      <tr bgcolor="#FFFFFF" height="2px">
       <td>
       </td>
      </tr>
      <tr>
       <td>
        <img height="8" src="../MainPageImages/baring.gif" width="100%"/>
       </td>
      </tr>
      <tr>
       <td align="center" background="../NMenu/bg_06[3].gif" bgcolor="#006600" colspan="2" height="26" width="100%">
        <a href="http://www.dhtml-menu-builder.com" style="display:none;visibility:hidden;">
         Drop Down Menu
        </a>
        <script type="text/javascript">
         <!--
stm_bm(["menu1a91",970,"","../blank.gif",0,"","",1,0,250,0,1000,1,0,0,"","100%",0,0,1,2,"default","hand","",1,25],this);
stm_bp("p0",[0,4,0,0,0,7,5,13,100,"stEffect(\"slip\")",-2,"progid:DXImageTransform.Microsoft.RandomDissolve(,enabled=0,Duration=0.60)",12,50,0,0,"#999999","transparent","../bg_01.gif",3,0,0,"#000000"]);
stm_ai("p0i0",[0,"NBP","","",-1,-1,0,"../index.aspx","_self","","","","",5,5,0,"","",13,12,0,1,1,"#993333",1,"#993333",1,"../bg_06[3].gif","../bg_06[3].gif",3,3,0,0,"#FFFFF7","#000000","#FFFFFF","#FFFFFF","bold 8pt Verdana","bold 8pt Verdana",0,0,"","","","",0,0,0]);
stm_bpx("p1","p0",[1,4,0,2,0,5,0,8,80,"stEffect(\"slip\")",-2,"progid:DXImageTransform.Microsoft.RandomDissolve(,enabled=0,Duration=0.30)",12,80,0,0,"#000000","#006600","",3,1,1]);
stm_aix("p1i0","p0i0",[0,"Bank\'s Profile","","",-1,-1,0,"../BankProfile/index.aspx","_self","","","","",0,0,0,"","",0,0,0,0,1,"#F9E0CA",1,"#000000",0,"","",3,1,0,0,"#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF","8pt Verdana","8pt Verdana"],0,18);
stm_ai("p1i1",[6,1,"#000000","",-1,-1,0]);
stm_aix("p1i2","p1i0",[0,"Governance","","",-1,-1,0,"","_self","","","","",0,0,0,"arrow2.gif","",8,8],0,18);
stm_bpx("p2","p1",[1,2,0,2,0,5,0,0]);
stm_aix("p2i0","p1i0",[0,"Senior Management","","",-1,-1,0,"../Governance/Smgt.aspx"]);
stm_aix("p2i1","p1i1",[]);
stm_aix("p2i2","p1i0",[0,"Board of Directors","","",-1,-1,0,"../Governance/BOD.aspx"]);
stm_aix("p2i3","p1i1",[]);
stm_aix("p2i4","p1i0",[0,"Directors\' Report","","",-1,-1,0,"../Governance/DirectorsReport.pdf","_blank"]);
stm_aix("p2i5","p1i1",[]);
stm_aix("p2i6","p1i0",[0,"Shareholding Pattern","","",-1,-1,0,"../SHPattern/index.aspx"]);
stm_aix("p2i7","p1i1",[]);
stm_aix("p2i8","p1i0",[0,"Auditors and Legal Advisors","","",-1,-1,0,"../Governance/Auditor-LegalAdvisor.aspx"]);
stm_ep();
stm_aix("p1i3","p1i1",[]);
stm_aix("p1i4","p1i2",[0,"Investor Relations","","",-1,-1,0,"../InvestorRelations/index.aspx"],0,18);
stm_bpx("p3","p2",[]);
stm_aix("p3i0","p1i0",[0,"Analyst Coverage","","",-1,-1,0,"../InvestorRelations/AnalystCoverage.aspx"]);
stm_aix("p3i1","p1i1",[]);
stm_aix("p3i2","p1i0",[0,"Media Reports & \r\nReleases","","",-1,-1,0,"../InvestorRelations/MediaReports-Releases.aspx"]);
stm_aix("p3i3","p1i1",[]);
stm_aix("p3i4","p1i0",[0,"Company News &\r\nAnnouncements","","",-1,-1,0,"../InvestorRelations/CompanyNewsAnnouncements.aspx"]);
stm_aix("p3i5","p1i1",[]);
stm_aix("p3i6","p1i0",[0,"Investor Relations\r\nTeam","","",-1,-1,0,"../InvestorRelations/InvestorRelationsTeam.aspx"]);
stm_aix("p3i7","p1i1",[]);
stm_aix("p3i8","p1i0",[0,"Investor Services","","",-1,-1,0,"../InvestorRelations/InvestorServices.aspx"]);
stm_aix("p3i9","p1i1",[]);
stm_aix("p3i10","p1i0",[0,"SECP Publications","","",-1,-1,0,"../InvestorRelations/SECP-Publications.aspx"]);
stm_aix("p3i11","p1i1",[]);
stm_aix("p3i12","p2i4",[0,"Corporate Social Responsibility","","",-1,-1,0,"../csr/index.aspx"]);
stm_aix("p3i13","p1i1",[]);
stm_aix("p3i14","p2i4",[0,"Research Publications","","",-1,-1,0,"../ResearchPublications/index.aspx"]);

stm_aix("p3i13","p1i1",[]);
stm_aix("p3i14","p2i4",[0,"Financial Statements","","",-1,-1,0,"../InvestorInformation/Group-Standalone-Fin-Statements.aspx"]);
stm_aix("p3i13","p1i1",[]);
stm_aix("p3i14","p2i4",[0,"Financial Highlights","","",-1,-1,0,"../InvestorInformation/Financial-Highlights.aspx"]);
stm_aix("p3i13","p1i1",[]);
stm_aix("p3i14","p2i4",[0,"Credit Ratings","","",-1,-1,0,"../InvestorInformation/CreditRatings.aspx"]);
stm_aix("p3i13","p1i1",[]);
stm_aix("p3i14","p2i4",[0,"Share Information","","",-1,-1,0,"../InvestorInformation/ShareInformation.aspx"]);


stm_ep();
stm_aix("p1i5","p1i1",[]);
stm_aix("p1i6","p1i0",[0,"Media","","",-1,-1,0,"../media/index.aspx"],0,18);
stm_aix("p1i7","p1i1",[]);
stm_aix("p1i8","p1i0",[0,"Election of Directors","","",-1,-1,0,"../eod/index.aspx"],0,18);
stm_ep();
stm_aix("p0i1","p1i1",[]);
stm_aix("p0i2","p0i0",[0,"Products & Sevices","","",-1,-1,0,"","_self","","","","",5,5,0,"","",-1,-1,0,1,1,"#FFFFF7",1,"#FFFFF7"]);
stm_bpx("p5","p1",[1,4,0,2,0,5,0,0,80,"stEffect(\"slip\")",-2,"progid:DXImageTransform.Microsoft.RandomDissolve(,enabled=0,Duration=0.30)",12,80,0,0,"#666666"]);
stm_aix("p5i0","p2i4",[0,"NBP Advance Services","","",-1,-1,0,"../AdvanceServices/AdvanceServices.jpg"]);
stm_aix("p5i1","p1i1",[]);
stm_aix("p5i2","p1i0",[0,"NBP Choice - Current Account","","",-1,-1,0,"../choice/index.aspx"]);
stm_aix("p5i3","p1i1",[]);
stm_aix("p5i4","p1i0",[0,"Asaan Account","","",-1,-1,0,"../asaan/index.aspx"]);
stm_aix("p5i3","p1i1",[]);
stm_aix("p5i4","p1i0",[0,"NBP Izafi Munafa Account","","",-1,-1,0,"../Izafi-Munafa-Account/index.aspx"]);
stm_aix("p5i3","p1i1",[]);
stm_aix("p5i4","p1i0",[0,"NBP Itmenan Account","","",-1,-1,0,"../ItmenanAccount/index.aspx"]);

stm_aix("p5i5","p1i1",[]);
stm_aix("p5i6","p1i0",[0,"Premium Aamdani","","",-1,-1,0,"../Aamdani/index.aspx"]);
stm_aix("p5i7","p1i1",[]);
stm_aix("p5i6","p1i0",[0,"NBP Plus TDC","","",-1,-1,0,"../tdc/index.aspx"]);
stm_aix("p5i7","p1i1",[]);
stm_aix("p5i8","p1i0",[0,"Premiun Saver","","",-1,-1,0,"../Premium/index.aspx"]);
stm_aix("p5i9","p1i1",[]);
stm_aix("p5i10","p1i0",[0,"Bancassurance","","",-1,-1,0,"#"]);
stm_bpx("p4","p2",[]);
stm_aix("p4i0","p1i0",[0,"State Life","","",-1,-1,0,"../bancassurance/index.aspx"]);
stm_aix("p4i1","p1i1",[]);
stm_aix("p4i2","p1i0",[0,"EFU Life","","",-1,-1,0,"../bancassurance/efu-Accelarated-Plan.aspx"]);
stm_aix("p4i3","p1i1",[]);
stm_aix("p4i4","p1i0",[0,"Jublee Life Insurance","","",-1,-1,0,"../bancassurance/Jublee-Jubilee-Bharosa-Plan.aspx"]);
stm_aix("p4i5","p1i1",[]);
stm_aix("p4i6","p1i0",[0,"Adamjeelife","","",-1,-1,0,"../bancassurance/Adamjeelife-Khidmat-Education-and-Marriage-Plan.aspx"]);
stm_aix("p4i7","p1i1",[]);
stm_aix("p4i8","p1i0",[0,"EFU Takaful","","",-1,-1,0,"../bancassurance/EFU-Takaful-Education-and-Marriage-Plan.aspx"]);
stm_aix("p4i7","p1i1",[]);
stm_aix("p4i8","p1i0",[0,"JLI Takaful","","",-1,-1,0,"../bancassurance/JLI-Takaful-Mustahkam-Plan.aspx"]);
stm_ep();
stm_aix("p5i11","p1i1",[]);
stm_aix("p5i12","p1i0",[0,"Saibaan","","",-1,-1,0,"../Saibaan/index.aspx"]);
stm_aix("p5i11","p1i1",[]);
stm_aix("p5i12","p1i0",[0,"NBP Roshan Ghar Solar Finance","","",-1,-1,0,"../RoshanGharSolarFinance/index.aspx"]);
stm_aix("p5i13","p1i1",[]);
stm_aix("p5i12","p1i0",[0,"Mera Ghar Mera Ashiana","","",-1,-1,0,"../Mera-Ghar-Mera-Ashiana/index.aspx"]);
stm_aix("p5i13","p1i1",[]);
stm_aix("p5i12","p1i0",[0,"Secured Running Finance(SRF)-Mortgage","","",-1,-1,0,"../SRFMortgage/index.aspx"]);
stm_aix("p5i13","p1i1",[]);
stm_aix("p5i14","p1i0",[0,"Advance Salary","","",-1,-1,0,"../advancesalary/index.aspx"]);
stm_aix("p5i15","p1i1",[]);
stm_aix("p5i14","p1i0",[0,"SME Financing","","",-1,-1,0,"../SMEFinancing/index.aspx"]);
stm_aix("p5i15","p1i1",[]);
stm_aix("p5i16","p1i0",[0,"EMV Debit Card","","",-1,-1,0,"../EMV-Debit-Card/index.aspx"]);
stm_aix("p5i17","p1i1",[]);
stm_aix("p5i18","p1i0",[0,"Gold Loan","","",-1,-1,0,"../CashnGold/index.aspx"]);
stm_aix("p5i19","p1i1",[]);
stm_aix("p5i20","p1i0",[0,"Kisan Taqat","","",-1,-1,0,"../KisanTaqat/index.aspx"]);
stm_aix("p5i21","p1i1",[]);
stm_aix("p5i22","p1i0",[0,"Kisan Dost","","",-1,-1,0,"../KisanDost/index.aspx"]);
stm_aix("p5i23","p1i1",[]);
stm_aix("p5i24","p1i0",[0,"NBP Digital","","",-1,-1,0,"../digital/index.aspx"]);
stm_aix("p5i25","p1i1",[]);
stm_aix("p5i24","p1i0",[0,"NBP Pegham","","",-1,-1,0,"../pegham/index.aspx"]);
stm_aix("p5i25","p1i1",[]);
stm_aix("p5i26","p1i0",[0,"NBP Online","","",-1,-1,0,"../NBPOnline/index.aspx"]);
stm_aix("p5i27","p1i1",[]);
stm_aix("p5i28","p1i0",[0,"NBP Helpline","","",-1,-1,0,"../HelpLine/index.aspx"]);
stm_aix("p5i29","p1i1",[]);
stm_ep();
stm_aix("p0i3","p1i1",[]);
stm_aix("p0i4","p0i0",[0,"Islamic Banking","","",-1,-1,0,"../Islamic/index.aspx","_self","","","","",5,5,0,"","",-1,-1]);
stm_bpx("p6","p5",[]);
stm_aix("p6i0","p1i0",[0,"Deposit Schemes","","",-1,-1,0,"../Islamic/DepositScheme.aspx"],0,18);
stm_aix("p6i1","p1i1",[]);
stm_aix("p6i0","p1i0",[0,"Advance Salary (Islamic)","","",-1,-1,0,"../advancesalaryIslamic/index.aspx"],0,18);
stm_aix("p6i1","p1i1",[]);
stm_aix("p6i2","p2i4",[0,"Weightages & Rates","","",-1,-1,0,"../IslamicFiles/PWHRates.pdf"],0,18);
stm_aix("p6i3","p1i1",[]);
stm_aix("p6i4","p1i0",[0,"Financing Facilities","","",-1,-1,0,"../Islamic/Financing.aspx"],0,18);
stm_aix("p6i5","p1i1",[]);
stm_aix("p6i6","p1i0",[0,"Other Services","","",-1,-1,0,"../Islamic/OtherServices.aspx"],0,18);
stm_aix("p6i7","p1i1",[]);
stm_aix("p6i8","p1i0",[0,"Contact","","",-1,-1,0,"../Islamic/IslamicContact.aspx"],0,18);
stm_aix("p6i9","p1i1",[]);

stm_aix("p6i10","p1i0",[0,"Shariah Board Profile","","",-1,-1,0,"../Islamic/ShariahAdvisorProfile.aspx"],0,18);
stm_aix("p6i9","p1i1",[]);

stm_aix("p6i10","p1i0",[0,"Shariah Portal","","",-1,-1,0,"../Islamic/ShariahPortal.aspx"],0,18);
stm_aix("p6i11","p1i1",[]);
stm_aix("p6i12","p1i0",[0,"Digital","","",-1,-1,0,"../Islamic/digital.aspx"],0,18);
stm_aix("p6i11","p1i1",[]);
stm_aix("p6i12","p1i0",[0,"Internet Banking","","",-1,-1,0,"../ib-islamic/index.aspx"],0,18);
stm_aix("p6i13","p1i1",[]);
stm_aix("p6i14","p1i0",[0,"Aitemaad Asaan Account","","",-1,-1,0,"../Islamic/Aitemaad-Asaan-Account.aspx"],0,18);
stm_aix("p6i15","p1i1",[]);
stm_aix("p6i16","p1i0",[0,"Aitemaad Hamsafar Auto Finance","","",-1,-1,0,"../Islamic/ahaf.aspx"],0,18);
stm_aix("p6i17","p1i1",[]);
stm_aix("p6i18","p1i0",[0,"Knowledge Centre","","",-1,-1,0,"../Islamic/IslamicKnowledgeCentre.aspx"],0,18);
stm_ep();
stm_aix("p0i5","p1i1",[]);
stm_aix("p0i6","p0i4",[0,"Financial Institutions","","",-1,-1,0,"../ficmd/index.aspx"]);
stm_bpx("p7","p5",[]);
stm_aix("p7i0","p1i0",[0,"Trade Services","","",-1,-1,0,"../ficmd/TradeSer.aspx"],0,18);
stm_aix("p7i1","p1i1",[]);

In [34]:
# divs = soup.find_all("tr", style="background-color:White;")
# #)
divs = soup.find("table", id="ctl00_ContentPlaceHolder1_GridView1")
print(divs)
len(divs)

<table border="0" cellpadding="2" cellspacing="2" height="205" id="ctl00_ContentPlaceHolder1_GridView1" rules="all" width="100%">
<tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl02_RateSheetNameLabel">NBP Rate Sheet 20 Nov 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-20-11-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl02_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl03_RateSheetNameLabel">NBP Rate Sheet 19 Nov 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-19-11-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl03_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl04_RateSheetNameLabel">NBP Rate Sheet 18 Nov 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-18-11-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl04_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl05_RateSheetNameLabel">NBP Rate Sheet 17 Nov 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-17-11-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl05_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl06_RateSheetNameLabel">NBP Rate Sheet 14 Nov 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-14-11-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl06_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl07_RateSheetNameLabel">NBP Rate Sheet 13 Nov 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-13-11-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl07_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl08_RateSheetNameLabel">NBP Rate Sheet 12 Nov 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-12-11-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl08_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl09_RateSheetNameLabel">NBP Rate Sheet 11 Nov 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-11-11-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl09_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl10_RateSheetNameLabel">NBP Rate Sheet 10 Nov 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-10-11-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl10_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl11_RateSheetNameLabel">NBP Rate Sheet 07 Nov 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-07-11-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl11_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl12_RateSheetNameLabel">NBP Rate Sheet 06 Nov 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-06-11-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl12_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl13_RateSheetNameLabel">NBP Rate Sheet 05 Nov 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-05-11-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl13_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl14_RateSheetNameLabel">NBP Rate Sheet 04 Nov 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-04-11-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl14_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl15_RateSheetNameLabel">NBP Rate Sheet 03 Nov 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-03-11-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl15_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl16_RateSheetNameLabel">NBP Rate Sheet 31 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-31-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl16_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl17_RateSheetNameLabel">NBP Rate Sheet 30 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-30-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl17_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl18_RateSheetNameLabel">NBP Rate Sheet 29 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-29-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl18_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl19_RateSheetNameLabel">NBP Rate Sheet 28 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-28-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl19_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl20_RateSheetNameLabel">NBP Rate Sheet 27 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-27-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl20_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl21_RateSheetNameLabel">NBP Rate Sheet 24 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-24-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl21_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl22_RateSheetNameLabel">NBP Rate Sheet 23 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-23-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl22_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl23_RateSheetNameLabel">NBP Rate Sheet 22 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-22-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl23_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl24_RateSheetNameLabel">NBP Rate Sheet 21 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-21-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl24_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl25_RateSheetNameLabel">NBP Rate Sheet 20 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-20-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl25_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl26_RateSheetNameLabel">NBP Rate Sheet 17 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-17-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl26_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl27_RateSheetNameLabel">NBP Rate Sheet 16 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-16-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl27_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl28_RateSheetNameLabel">NBP Rate Sheet 15 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-15-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl28_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl29_RateSheetNameLabel">NBP Rate Sheet 14 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-14-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl29_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl30_RateSheetNameLabel">NBP Rate Sheet 13 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-13-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl30_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl31_RateSheetNameLabel">NBP Rate Sheet 10 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-10-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl31_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl32_RateSheetNameLabel">NBP Rate Sheet 09 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-09-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl32_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl33_RateSheetNameLabel">NBP Rate Sheet 08 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-08-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl33_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl34_RateSheetNameLabel">NBP Rate Sheet 07 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-07-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl34_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl35_RateSheetNameLabel">NBP Rate Sheet 06 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-06-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl35_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl36_RateSheetNameLabel">NBP Rate Sheet 03 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-03-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl36_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl37_RateSheetNameLabel">NBP Rate Sheet 02 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-02-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl37_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl38_RateSheetNameLabel">NBP Rate Sheet 01 Oct 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-01-10-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl38_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl39_RateSheetNameLabel">NBP Rate Sheet 30 Sep 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-30-09-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl39_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl40_RateSheetNameLabel">NBP Rate Sheet 29 Sep 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-29-09-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl40_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl41_RateSheetNameLabel">NBP Rate Sheet 26 Sep 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-26-09-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl41_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl42_RateSheetNameLabel">NBP Rate Sheet 25 Sep 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-25-09-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl42_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl43_RateSheetNameLabel">NBP Rate Sheet 24 Sep 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-24-09-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl43_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl44_RateSheetNameLabel">NBP Rate Sheet 23 Sep 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-23-09-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl44_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl45_RateSheetNameLabel">NBP Rate Sheet 22 Sep 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-22-09-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl45_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl46_RateSheetNameLabel">NBP Rate Sheet 19 Sep 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-19-09-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl46_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="White">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl47_RateSheetNameLabel">NBP Rate Sheet 18 Sep 2025</span>
</font></td><td align="right">
<a href="../RateSheetFiles/NBP-RateSheet-18-09-2025.pdf" id="ctl00_ContentPlaceHolder1_GridView1_ctl47_ReportLink" target="_blank"><font face="Verdana" size="2">View Now</font></a>
<br/>
</td>
</tr><tr bgcolor="#EBEBEB">
<td align="left" valign="middle" width="85%"><font face="Verdana">
<span id="ctl00_ContentPlaceHolder1_GridView1_ctl48_RateSheetNameLabel">NBP Rate Sheet 17 Sep 2025</span>
</font></td><td align="right">

2594

In [39]:
rows = divs.find_all("tr")
rows
len(rows)

2592

In [ ]:
# list=[]
# for i in rows:
#     dic={
#         'pdf_name':'',
#         'pdf_url':'',
#     }
#     dic['pdf_name']=i.find('span').text.strip()
#     dic['pdf_url']=i.find('a')['href']
    
#     list.append(dic)
# list
# df=pd.DataFrame(list)
# df

,pdf_name,pdf_url
0,NBP Rate Sheet 20 Nov 2025,../RateSheetFiles/NBP-RateSheet-20-11-2025.pdf
1,NBP Rate Sheet 19 Nov 2025,../RateSheetFiles/NBP-RateSheet-19-11-2025.pdf
2,NBP Rate Sheet 18 Nov 2025,../RateSheetFiles/NBP-RateSheet-18-11-2025.pdf
3,NBP Rate Sheet 17 Nov 2025,../RateSheetFiles/NBP-RateSheet-17-11-2025.pdf
4,NBP Rate Sheet 14 Nov 2025,../RateSheetFiles/NBP-RateSheet-14-11-2025.pdf
...,...,...
2587,NBP Rate Sheet 11 May 2015,../RateSheetFiles/NBP-RateSheet-11-05-2015.pdf
2588,NBP Rate Sheet 08 May 2015,../RateSheetFiles/NBP-RateSheet-08-05-2015.pdf
2589,NBP Rate Sheet 07 May 2015,../RateSheetFiles/NBP-RateSheet-07-05-2015.pdf
2590,NBP Rate Sheet 06 May 2015,../RateSheetFiles/NBP-RateSheet-06-05-2015.pdf
2591,NBP Rate Sheet 05 May 2015,../RateSheetFiles/NBP-RateSheet-05-05-2015.pdf

In [43]:
# soup=BeautifulSoup(r.text,'html.parser')
# table=soup.find('table',id='ctl00_ContentPlaceHolder1_GridView1')
# tr=table.find_all('tr')
# tr
list=[]
for i in rows:
    dic={
        'pdf_name':'',
        'pdf_url':'',
    }
    dic['pdf_name']=i.find('span').text.strip()
    dic['pdf_url']=i.find('a')['href']
    base_url='https://www.nbp.com.pk/'
    actral_url=base_url+dic['pdf_url']
    dic['pdf_url']=actral_url 
    list.append(dic)
list
df=pd.DataFrame(list)
df

,pdf_name,pdf_url
0,NBP Rate Sheet 20 Nov 2025,https://www.nbp.com.pk/../RateSheetFiles/NBP-R...
1,NBP Rate Sheet 19 Nov 2025,https://www.nbp.com.pk/../RateSheetFiles/NBP-R...
2,NBP Rate Sheet 18 Nov 2025,https://www.nbp.com.pk/../RateSheetFiles/NBP-R...
3,NBP Rate Sheet 17 Nov 2025,https://www.nbp.com.pk/../RateSheetFiles/NBP-R...
4,NBP Rate Sheet 14 Nov 2025,https://www.nbp.com.pk/../RateSheetFiles/NBP-R...
...,...,...
2587,NBP Rate Sheet 11 May 2015,https://www.nbp.com.pk/../RateSheetFiles/NBP-R...
2588,NBP Rate Sheet 08 May 2015,https://www.nbp.com.pk/../RateSheetFiles/NBP-R...
2589,NBP Rate Sheet 07 May 2015,https://www.nbp.com.pk/../RateSheetFiles/NBP-R...
2590,NBP Rate Sheet 06 May 2015,https://www.nbp.com.pk/../RateSheetFiles/NBP-R...
2591,NBP Rate Sheet 05 May 2015,https://www.nbp.com.pk/../RateSheetFiles/NBP-R...