In [3]:
import pandas as pd
import time
import requests
from bs4 import BeautifulSoup
from selenium import webdriver

driver  = webdriver.Chrome()
url   = "https://getlatka.com/saas-companies?page=1"
driver.get(url)
time.sleep(5)
driver.find_element("xpath","//button[@class='newsletter-popup__close']").click()
time.sleep(2)

In [ ]:
soup = BeautifulSoup(driver.page_source,"html")
trs = soup.find_all("tr",class_ = "data-table_row__aX_dq")
list=[]
for i in range(0,20,1):
    tds_of_each_row = trs[i].find_all("td") # trs[0] matlb 1st row of data, next row k leye trs[1]

    dic = {
        "name": ""
    }

    second_colum_of_row = tds_of_each_row[1] # q k second col me company data han

    all_a_of_2nd_td = second_colum_of_row.find_all("a") # find all a tags

    dic["name"] = all_a_of_2nd_td[0].text # fisrt a k tag k andar company name

    for a in all_a_of_2nd_td[1:]: #baki sary links `a tag`` k andar han os k leye loop lagyga. k automatically key/column name with value pick kary 
        key  = a["aria-label"] # `a` tag k attribute `aria-label` mein key/column  name houwta
        value = a["href"] # `a` tag k attribute `href` mein url/link houwta
        # print(f"{key} = {value}")
        dic[key] = value # har row me jis social media links huengy wo automatically save hun jaengy. jaisy k 1st row me 2 links and last row me 5 links. toh humra code chal jayga dono situation py without any error

    dic["company location"]  = tds_of_each_row[-2].text # company location sary tds me sy second last `td tag`` me han. jis k leye -2 lagaya
    dic["company founder"]  =tds_of_each_row[-6].text.strip() # company founder sary tds me sy last 6th `td tag`` me han. jis k leye -6 lagaya
    list.append(dic.copy())
    list

In [34]:
df=pd.DataFrame(list)
df

,name,Company linkedIn,website url,company location,company founder,Company Twitter,Company Crunchbase,Company facebook
0,Nue.io,http://www.linkedin.com/company/nue-io?ref=get...,//nue.io/?ref=getlatka.com,United States,Mark Walker,NaN,NaN,NaN
1,briq,https://www.linkedin.com/company/briqhq/?ref=g...,//briq.com/?ref=getlatka.com,(US),Ron Goldshmidt,NaN,NaN,NaN
2,Arcads,https://www.linkedin.com/company/arcads-ai/?re...,//arcads.ai/?ref=getlatka.com,France,,NaN,NaN,NaN
3,BetterPic,NaN,//betterpic.io/?ref=getlatka.com,Estonia,,NaN,NaN,NaN
4,SubMagic,https://www.linkedin.com/company/submagic?ref=...,//submagic.co/?ref=getlatka.com,France,David Zitoun,NaN,NaN,NaN
5,Zapmail,https://www.linkedin.com/company/zapmail-ai/?r...,//zapmail.ai/?ref=getlatka.com,(US),Alan D'Souza,NaN,NaN,NaN
6,MarsX.dev,https://www.linkedin.com/company/marsx?ref=get...,//marsx.dev/?ref=getlatka.com,(US),John Rush,https://twitter.com/marsxdev?ref=getlatka.com,NaN,NaN
7,Cal AI,https://www.linkedin.com/company/cal-ai-app/?r...,//calai.app/?ref=getlatka.com,(US),Jake Castillo,NaN,NaN,NaN
8,Capacity,https://www.linkedin.com/company/teamcapacity?...,//capacity.com/?ref=getlatka.com,(US),David Karandish,NaN,https://www.crunchbase.com/organization/capaci...,NaN
9,TripleDart,https://www.linkedin.com/company/tripledart-di...,//tripledart.com/?ref=getlatka.com,(US),Shiyam Sunder,https://twitter.com/Tripledart_?ref=getlatka.com,NaN,NaN
10,Voxpopme,https://www.linkedin.com/company/voxpopme?ref=...,//voxpopme.com/?ref=getlatka.com,(US),Andrew Barraclough,NaN,https://www.crunchbase.com/organization/voxpop...,NaN
11,Pendo,https://www.linkedin.com/company/pendo-io/?ref...,//pendo.io/?ref=getlatka.com,(US),Todd Olson,https://twitter.com/pendoio?ref=getlatka.com,https://www.crunchbase.com/organization/pendo-...,https://www.facebook.com/Pendoio/?ref=getlatka...
12,Issuu,https://www.linkedin.com/company/issuu/?ref=ge...,//issuu.com/?ref=getlatka.com,(US),,NaN,https://www.crunchbase.com/organization/issuu?...,NaN
13,Ninety.io,https://www.linkedin.com/company/ninety-io?ref...,//ninety.io/?ref=getlatka.com,(US),Tim Weerasiri,NaN,https://www.crunchbase.com/organization/ninety...,NaN
14,Reveleer,https://www.linkedin.com/company/reveleer/?ref...,//reveleer.com/?ref=getlatka.com,(US),,NaN,https://www.crunchbase.com/organization/revele...,NaN
15,Proposify,https://www.linkedin.com/company/proposify/?re...,//proposify.com/?ref=getlatka.com,(CA),Kyle Racki,NaN,https://www.crunchbase.com/organization/propos...,NaN
16,BrightEdge,https://www.linkedin.com/company/brightedge?re...,//brightedge.com/?ref=getlatka.com,(US),Jim Yu,http://twitter.com/brightedge?ref=getlatka.com,https://www.crunchbase.com/organization/bright...,https://www.facebook.com/seoplatform?ref=getla...
17,Celigo,https://www.linkedin.com/company/celigo-inc?re...,//celigo.com/?ref=getlatka.com,(US),Jan Arendtsz,https://twitter.com/celigoinc?ref=getlatka.com,https://www.crunchbase.com/organization/celigo...,https://www.facebook.com/CeligoInc/?ref=getlat...
18,Netcore Cloud,https://www.linkedin.com/company/netcore-cloud...,//netcorecloud.com/?ref=getlatka.com,(IN),Rajesh Jain,https://twitter.com/netcore_cloud?ref=getlatka...,https://www.crunchbase.com/organization/netcor...,https://www.facebook.com/NetcoreCloud/?ref=get...
19,Hootsuite,https://ca.linkedin.com/company/hootsuite?ref=...,//hootsuite.com/?ref=getlatka.com,(CA),Irina Novoselsky,https://twitter.com/hootsuite?ref=getlatka.com,https://www.crunchbase.com/organization/hootsu...,https://www.facebook.com/hootsuite?ref=getlatk...

In [ ]:
import pandas as pd
import time
import requests
from bs4 import BeautifulSoup
from selenium import webdriver

driver  = webdriver.Chrome()
main_url   = "https://getlatka.com/saas-companies?page="

list=[]
for i in range(1,6):
    url=main_url+str(i)
    driver.get(url)
    time.sleep(5)
    try:
        driver.find_element("xpath","//button[@class='newsletter-popup__close']").click()
        time.sleep(2)
    except:
        pass
    soup = BeautifulSoup(driver.page_source,"html")
    trs = soup.find_all("tr",class_ = "data-table_row__aX_dq")
    
    for i in range(0,20,1):
        tds_of_each_row = trs[i].find_all("td") # trs[0] matlb 1st row of data, next row k leye trs[1]

        dic = {
            "name": ""
        }

        second_colum_of_row = tds_of_each_row[1] # q k second col me company data han

        all_a_of_2nd_td = second_colum_of_row.find_all("a") # find all a tags

        dic["name"] = all_a_of_2nd_td[0].text # fisrt a k tag k andar company name

        for a in all_a_of_2nd_td[1:]: #baki sary links `a tag`` k andar han os k leye loop lagyga. k automatically key/column name with value pick kary 
            key  = a["aria-label"] # `a` tag k attribute `aria-label` mein key/column  name houwta
            value = a["href"] # `a` tag k attribute `href` mein url/link houwta
            # print(f"{key} = {value}")
            dic[key] = value # har row me jis social media links huengy wo automatically save hun jaengy. jaisy k 1st row me 2 links and last row me 5 links. toh humra code chal jayga dono situation py without any error

        dic["company location"]  = tds_of_each_row[-2].text # company location sary tds me sy second last `td tag`` me han. jis k leye -2 lagaya
        dic["company founder"]  =tds_of_each_row[-6].text.strip() # company founder sary tds me sy last 6th `td tag`` me han. jis k leye -6 lagaya
        list.append(dic.copy())
        list

In [42]:
df=pd.DataFrame(list)
df

,name,Company linkedIn,website url,company location,company founder,Company Twitter,Company Crunchbase,Company facebook
0,Nue.io,http://www.linkedin.com/company/nue-io?ref=get...,//nue.io/?ref=getlatka.com,United States,Mark Walker,NaN,NaN,NaN
1,briq,https://www.linkedin.com/company/briqhq/?ref=g...,//briq.com/?ref=getlatka.com,(US),Ron Goldshmidt,NaN,NaN,NaN
2,Arcads,https://www.linkedin.com/company/arcads-ai/?re...,//arcads.ai/?ref=getlatka.com,France,,NaN,NaN,NaN
3,BetterPic,NaN,//betterpic.io/?ref=getlatka.com,Estonia,,NaN,NaN,NaN
4,SubMagic,https://www.linkedin.com/company/submagic?ref=...,//submagic.co/?ref=getlatka.com,France,David Zitoun,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
95,involve.ai,NaN,//involve.ai/?ref=getlatka.com,(US),Gaurav Bhattacharya,https://twitter.com/involve_ai?ref=getlatka.com,https://www.crunchbase.com/organization/involv...,NaN
96,Monite,https://www.linkedin.com/company/monitehq?ref=...,//monite.com/?ref=getlatka.com,Germany,Ivan Maryasin,NaN,NaN,NaN
97,Verifiet,https://www.linkedin.com/company/verifiet?ref=...,//verifiet.com/?ref=getlatka.com,(US),Farhan Afsahi,NaN,NaN,NaN
98,Jugl,NaN,//jugl.com/?ref=getlatka.com,(US),Arun Kumar,NaN,NaN,NaN
99,Shipit,NaN,//shipit.cl/?ref=getlatka.com,Chile,Allan Guiloff,NaN,https://www.crunchbase.com/organization/shipit...,NaN

In [43]:
df.to_csv('getlatka_1to5_page.csv',index=False)